name: flare_flutter
description: Vector design and runtime animation for Flutter.
version: 3.0.2
homepage: https://github.com/2d-inc/Flare-Flutter

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
